name: Analyze

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: analyze
  cancel-in-progress: true

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: analyze
        name: Analyze Lighthouse audits
        run: pipenv run python -m newshomepages.analyze lighthouse;
        shell: bash

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./extracts
          git commit -m "Update lighthouse analysis" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash

  drudge-hyperlinks:
    name: Drudge hyperlinks
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: analyze
        name: Analyze Drudge hyperlinks
        run: pipenv run python -m newshomepages.analyze drudge-hyperlinks;
        shell: bash

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./extracts
          git commit -m "Update Drudge hyperlinks analysis" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash

      - id: save
        name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracts
          path: ./extracts
          if-no-files-found: error

  drudge-entities:
    name: Drudge entities
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: install-spacy
        name: Install Spacy language dictionary
        run: pipenv run python -m spacy download en_core_web_lg
        shell: bash

      - id: analyze
        name: Analyze Drudge hyperlinks
        run: pipenv run python -m newshomepages.analyze drudge-entities;
        shell: bash

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./extracts
          git commit -m "Update Drudge entities analysis" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash

      - id: save
        name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracts
          path: ./extracts
          if-no-files-found: error

  us-right-wing-hyperlinks:
    name: U.S. right wing hyperlinks
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: analyze
        name: Analyze Drudge hyperlinks
        run: pipenv run python -m newshomepages.analyze us-right-wing-hyperlinks;
        shell: bash

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./extracts
          git commit -m "Update U.S. right wing hyperlinks analysis" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash

      - id: save
        name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: extracts
          path: ./extracts
          if-no-files-found: error