name: "Archive: Russia"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-country-workflow.yml@main
    with:
      country: RU
    secrets: inherit
