name: "Archive: Iowa"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * MON,WED,FRI"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-bundle-workflow.yml@main
    with:
      bundle: iowa
    secrets: inherit
