name: "Archive: France"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-country-workflow.yml@main
    with:
      country: FR
    secrets: inherit
