name: "Archive: Israel"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-country-workflow.yml@main
    with:
      country: IL
    secrets: inherit
