name: "Archive: Brazil"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-country-workflow.yml@main
    with:
      country: BR
    secrets: inherit
